### ISSUE TITLE
Cannot find module "."

### ISSUE THREAD

**Issue by bensleveritt** [mmacaula/cesium-webpack#4]
When using the source method, I'm hitting an error on load

```
Error constructing CesiumWidget. (CesiumWidget.js:629)
Visit <a href="http://get.webgl.org">http://get.webgl.org</a> to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:
Error: Cannot find module "."
Error: Cannot find module "."
    at webpackMissingModule (buildModuleUrl.js:76)
    at buildModuleUrl (buildModuleUrl.js:76)
    at new Globe (Globe.js:118)
    at new CesiumWidget (CesiumWidget.js:279)
    at new Viewer (Viewer.js:398)
    at Object.<anonymous> (index.jsx:8)
    at __webpack_require__ (bootstrap 2fc8eea…:19)
    at Object.<anonymous> (app.js:188626)
    at __webpack_require__ (bootstrap 2fc8eea…:19)
    at Object.<anonymous> (client?6c0a:102)
    at __webpack_require__ (bootstrap 2fc8eea…:19)
    at Object.<anonymous> (amd-options.js:1)
    at __webpack_require__ (bootstrap 2fc8eea…:19)
    at bootstrap 2fc8eea…:63
    at bootstrap 2fc8eea…:63
```

This is with `"cesium": "^1.23.0"`.

@mmacaula Are you seeing the same issue with 1.16+?

**Comment by mmacaula** [comment]
@bensleveritt, I created a branch with a 1.23 version of cesium [here](https://github.com/mmacaula/cesium-webpack/tree/try-1.23) and everything worked fine for me, no errors.  Can you give more details?  what have you done differently from that branch?   Do you have the same issue on that branch?

**Comment by bensleveritt** [comment]
Thanks for looking into this.

I checked out your branch and hit against this error (after installing `webpack` and `webpack-dev-server`. I presume you've got them as globals):

```
...
  [634] ./~/cesium/Source/Widgets/VRButton/VRButton.js 5.7 kB {0} [built]
  [635] ./~/cesium/Source/Widgets/VRButton/VRButtonViewModel.js 6.91 kB {0} [built]

WARNING in ./~/cesium/Source/ThirdParty/earcut-2.1.1.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/cesium/Source/ThirdParty/earcut-2.1.1.js 1:479-486

ERROR in Path must be a string. Received undefined
```

Not sure where to start debugging that one.

Are you using the `postInstall.sh` script in this example? I see it runs, but there doesn't seem to be any reference to the copied files in the Webpack build list (see module 635 references the `cesium` source).

With regards to differences, it seems very similar, but I'm using Webpack 2 with Babel/React, so there might be some incompatibilities there.

**Comment by bensleveritt** [comment]
Ah, I think I understand the cause of my first issue. Seems Webpack has replaced a `require` reference with the error message:

```
    function buildModuleUrl(moduleID) {
        if (!defined(implementation)) {
            //select implementation
            if (defined(require.toUrl)) {
                implementation = buildModuleUrlFromRequireToUrl;
            } else {
                implementation = buildModuleUrlFromBaseUrl;
            }
        }
```

with 

```
    function buildModuleUrl(moduleID) {
        if (!defined(implementation)) {
            //select implementation
            if (defined(!(
                    function webpackMissingModule() {
                        var e = new Error("Cannot find module \".\"");
                        e.code = 'MODULE_NOT_FOUND';
                        throw e;
                     }()
                ).toUrl)) 
```

where the `require` reference has been unceremoniously replaced. Frustratingly this is a check to see if require is available, and switch loading implementations based on it.

This might just be a completely incompatible combination of Cesium's usage of Require and Webpack.

**Comment by bensleveritt** [comment]
In the basic example of rendering a globe, there is another instance of checking for `require.toUrl`. Forcing the check into the `else` clause (replacing the check with just `false` in the source files) works just fine.

Now I just have to figure out how to persuade Webpack to leave `require` intact in these contexts. I wonder if the Cesium folks would be interested in this?

**Comment by bensleveritt** [comment]
And now I can conclude that this is most likely a Webpack 2 bug (webpack/webpack#2670).

Thanks anyway.

**Comment by erikostling** [comment]
Did you ever find a solution to this @bensleveritt? Running into the same issue…

**Comment by jimmyangel** [comment]
I ran into the same issue with webpack 2. The only way I have been able to use webpack 2 with Cesium is as 'external' loaded from <script> tag.

Are you planning to make this work on webpack 2?

**Comment by jduhls** [comment]
These must be in your webpack config:

```javascript
module: {
    unknownContextCritical: false,
    unknownContextRegExp: /^.\/.*$/,
    ...
}
````

...but now I am stuck with some amd issue of relative paths not loading correctly:

```
GET http://localhost:8080/Workers/Core/Ellipsoid.js 404 (Not Found)
Uncaught Error: importScripts failed for Workers/createVerticesFromHeightmap at http://localhost:8080/Workers/createVerticesFromHeightmap.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (cesiumWorkerBootstrapper.js:188)
    at Function.req.load (cesiumWorkerBootstrapper.js:1967)
    at Object.load (cesiumWorkerBootstrapper.js:1690)
    at Module.load (cesiumWorkerBootstrapper.js:852)
    at Module.fetch (cesiumWorkerBootstrapper.js:842)
    at Module.check (cesiumWorkerBootstrapper.js:874)
    at Module.enable (cesiumWorkerBootstrapper.js:1188)
    at Object.enable (cesiumWorkerBootstrapper.js:1561)
    at Module.<anonymous> (cesiumWorkerBootstrapper.js:1173)
    at cesiumWorkerBootstrapper.js:153
```

It SHOULD load: ```http://localhost:8080/Core/Ellipsoid.js```

It's in the cesium forums but no resolution there either:

https://groups.google.com/forum/#!msg/cesium-dev/N2o0DZRVr58/6QEDCQX2BQAJ

**Comment by jduhls** [comment]
I hacked ```Workers/cesiumWorkerBootsrapper.js``` and commented out the call to ```trimDots(name);``` and everything loads, albeit slowly. Not sure of the exact side effects yet. I have not compiled, only using webpack dev server at the moment. All the load paths look a little wacky but are loading:

![screen shot 2017-05-16 at 12 54 00 pm](https://cloud.githubusercontent.com/assets/3170699/26120725/4a041b46-3a37-11e7-98c1-5ed8a6dc5725.png)

**Comment by jduhls** [comment]
Compile was not successful. I went back to working from pre-built cesium for the time being.

**Comment by W07FP4X** [comment]
For folks still being blocked by this issue,

```
//Resolves webpack 2 issue where Cesium lib is using an if (require.toUrl) check to define loading 
//behaviour, but Webpack replaces it with "Cannot find module ".""

unknownContextRegExp: /^.\/.*$/,
```

**Comment by ghost** [comment]
I have this problem as well. I am using the Vue.js + webpack and there is error with the paths. Has anybody found a solution?

**Comment by diegonc** [comment]
Can anybody explain what the unknownContextRegExp does? and why that regex and not other? :thinking:

**Comment by mmacaula** [comment]
@diegonc as mentioned in this project's Readme, cesium build dynamic urls to require and webpack likes to know all the potential required items up front.  

For those others following this issue, I suggest you follow https://github.com/AnalyticalGraphicsInc/cesium/issues/5816

**Comment by aleksandrmelnyk** [comment]
For those who have issues like this:

> I have this problem as well. I am using the Vue.js + webpack and there is error with the paths. Has anybody found a solution?

don't forget to fix base url like this:
```
new webpack.DefinePlugin({
      // Define relative base path in cesium for loading assets
      CESIUM_BASE_URL: JSON.stringify('/')
    }),
```
in webpack config plugins section
