### ISSUE TITLE
Updated example if you want it...

### ISSUE THREAD

**Issue by lucastheisen** [mmacaula/cesium-webpack#5]
I just went through your tutorial and decided to try it out myself.  In doing so, i created an updated version of your project.  I know its not a pull request cause I dont really understand the `source` version, but if you want, you could update your example:

https://gitlab.com/pastdev/cesium-webpack

**Comment by mmacaula** [comment]
Thanks @lucastheisen!  I also updated the readme to point to the 'official' project hosted by the Cesium team!
