### ISSUE TITLE
Path must be a string webpack

### ISSUE THREAD

**Issue by CHBaker** [mmacaula/cesium-webpack#7]
after following tutorial steps, and npm installing the webpack html loader plugin, 
I run the app on 8080 and get this error:
```
ERROR in ./app.js
Module not found: Error: Can't resolve 'style' in '/home/hawtballa/Desktop/cesium-webpack-one/using-source'
 @ ./app.js 1:0-44
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js

ERROR in Path must be a string. Received undefined
```

which comes after many, many other errors. this is what the page displayed
`TypeError: Path must be a string. Received undefined`

**Comment by mmacaula** [comment]
Project is deprecated, see updated readme
